### ISSUE TITLE
Message received in wrong date only in iOS

### ISSUE THREAD

**Issue by saumyadippramanik** [QuickBlox/quickblox-react-native-sdk#29] opened 2021-02-10 15:37 UTC
I am getting wrong date ("dateSent": 2147483647000 => Tue Jan 19 2038 08:44:07 GMT+0530) in payload recieved from following functions:

```
  addMessageListener = () => {
    const emitter = new NativeEventEmitter(QB.chat);
    this.subscription = emitter.addListener(
      QB.chat.EVENT_TYPE.RECEIVED_NEW_MESSAGE,
      this.receivedNewMessage,
    );
  };

  receivedNewMessage = event => {
    const {payload} = event;
    this.updateMessageList(payload);
  };
```

**Received Payload:**
 {"body": "Hey there", "dateSent": 2147483647000, "delayed": false, "deliveredIds": [124026220], "dialogId": "6022ac7ca0eb47532e51b441", "id": "6023fcb22b727a9731df1bc3", "markable": true, "properties": {"date_sent": "2147483647", "dialog_id": "6022ac7ca0eb47532e51b441", "message_id": "6023fcb22b727a9731df1bc3", "save_to_history": "1"}, "readIds": [124026220], "recipientId": 124026270, "saveToHistory": true, "senderId": 124026220}

The issue is only in iOS, android is working fine. 
Strangely, when the message is received in Chat Dialog history, the date is coming correct and I have checked in the QuickBlox portal as well, the entry of the message is correct there.

**Versions I am Using:**
"quickblox-react-native-sdk": "^0.5.2-beta"
"react-native": "0.62.2"

Please help ASAP!

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:42
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 14:27
@hussnainghani Hello,

This is Nikolay from QuickBlox support.

Please try updating the SDK and let me know if the issue is still relevant:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)

If yes, please provide me with the following points:
1. Steps to reproduce the issue.
2. Full logs.
3. iOS version.
4. Information from react-native info.
5. Information from npm list.
6. iPhone models.

**Comment by ghost** [comment] 2021-12-07 14:23
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:23 UTC
