### ISSUE TITLE
Possibility to connect to the chat with existing session token

### ISSUE THREAD

**Issue by kasterlod** [QuickBlox/quickblox-react-native-sdk#13] opened 2020-05-13 21:31 UTC
### Hello!

Short context:
**We're using QB on the web and connecting in that way:**
    `QB.chat.connect({ jid: <jid>, password: <sessionToken> })`

**Why?**
Users are created on backend side, and we don't want to send passwords to front end layer.

### QUESTION
Is it possible to do the same way with this SDK? If not, what period of time can be expected to do this?

lots of greetings!

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 13:18
@kasterlod Hello,

This is Nikolay from QuickBlox support.

Please let me know if the question is still relevant.

**Comment by ghost** [comment] 2021-12-07 14:19
@kasterlod The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:19 UTC
