### ISSUE TITLE
how to avoid echo and noise in quickblox

### ISSUE THREAD

**Issue by ArminShahamati** [QuickBlox/quickblox-react-native-sdk#24] opened 2020-11-24 11:29 UTC
In many models of phone 
when a video call connected a user hears his own voice echo

**Comment by ArminShahamati** [comment] 2020-11-24 13:56
I want to mute local video stream

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:42
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 13:47
@ArminShahamati Hello,

This is Nikolay from QuickBlox support.

Echos usually happen when a microphone driver doesn't support echo cancellation, when a microphone is too sensitive, speakers are turned on too loud, or interference from other electronic devices nearby.
Echoing can be avoided by wearing headphones.

Please make sure that the devices are in different locations. Also, please specify the distance between the devices.

If the issue persists, we will need the following points:

1. Please let us know if the issue can be reproduced with the latest version of the SDK:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)
2. Please try reproducing the issue on our sample:
[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample)
3. Platform where the issue is reproduced (Android, iOS, or both).
4. Version of the platform (e.g. Android 11, iOS 13).
5. Device models.
6. React Native version.
7. Information from react-native info.
8. Information from npm list.
9. Is this issue intermittent or permanent?
10. Please provide us with full REST + XMPP + WebRTC logs as an attachment to this ticket in .txt format.
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by ghost** [comment] 2021-12-07 14:22
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:22 UTC
