### ISSUE TITLE
DIALOGS_EDIT_SUCCESS not working while performing with removeUsers  in Android

### ISSUE THREAD

**Issue by nithiniLeaf** [QuickBlox/quickblox-react-native-sdk#31] opened 2021-04-22 13:19 UTC

**Comment by ghost** [comment] 2021-10-06 12:36
@nithiniLeaf Hello,

This is Nikolay from QuickBlox support.

Please try upgrading the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)

If the issue persists, please provide me with the following points:
1. A detailed description of the issue.
2. Please provide full REST + XMPP + WebRTC logs as an attachment in .txt format.
You may use this guide: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)
3. Steps to reproduce the issue.
4. Platform where the issue is reproduced (Android, iOS, or both).
5. Version of the platform (e.g. Android 11, iOS 13).
6. Information from react-native info.
7. Information from npm list.

**Comment by ghost** [comment] 2021-12-07 14:23
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:23 UTC
