### ISSUE TITLE
error while getting current session on android

### ISSUE THREAD

**Issue by russelRajitha** [QuickBlox/quickblox-react-native-sdk#9] opened 2020-04-10 15:50 UTC
I am using latest react native version and when i was tryning to check current session app is getting crashed. Here is the log

`2020-04-10 21:14:11.118 5874-5989/com.fresh E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.quickblox.auth.session.QBSession.getToken()' on a null object reference
        at com.quickblox.reactnative.auth.AuthMapper.qbSessionToMap(AuthMapper.java:73)
        at com.quickblox.reactnative.auth.AuthModule.getSession(AuthModule.java:111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by ghost** [comment] 2020-05-28 14:26
Hello @russelRajitha 

Try to reproduce the reported behavior on clear QuickBlox ReactNative sample: https://github.com/QuickBlox/quickblox-react-native-samples/

If the reported behavior reproduces there, provide me with the detailed reproducing steps and full logs from application launching till the issue occurs (error code should be included). 

Looking forward to your reply.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 12:20
@russelRajitha 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If yes, please provide the information requested in the previous comment.

**Comment by ghost** [comment] 2021-12-07 14:19
@russelRajitha The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:19 UTC
