### ISSUE TITLE
my app crashes when its receive notification

### ISSUE THREAD

**Issue by medghazdali** [QuickBlox/quickblox-react-native-sdk#19] opened 2020-08-16 20:22 UTC
when i send notification from admin panel  my app crashes , or from user to user like call when the app in background.
any help please or idea ? thank you

**Comment by sagar-chhatrola** [comment] 2020-09-23 11:52
Same thing happening for me. When I call other user through quickblox , other user side app got crashed.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 13:02
Please refer to our documentation:
https://docs.quickblox.com/docs/react-native-push-notifications

Also, you may use this guide to the configuring push notifications:
https://help.quickblox.com/article/268-configuration-of-chat-and-video-push-notifications

Please keep in mind that managing and configuring push notifications in the background mode or killed state is not a part of QuickBlox SDK's and the implementation is up to the client side.

If the issue persists, please provide me with the following points:
1. Steps to reproduce the issue.
2. Full logs.
3. Version of QuickBlox React Native SDK.
4. Platform where the issue is reproduced (Android, iOS, or both).
5. Version of the platform (e.g. Android 11, iOS 13).
6. Device models.
7. React Native version.
8. Information from react-native info.
9. Information from npm list.

**Comment by ghost** [comment] 2021-12-07 14:21
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:21 UTC
