### ISSUE TITLE
Unable to join multiple dialogs

### ISSUE THREAD

**Issue by Gusakovskyi** [QuickBlox/quickblox-react-native-sdk#12] opened 2020-05-08 10:08 UTC
After retrieving a list of dialogs i am trying to join each of them in loop. But only first join is successful and others return error:
`You are already joined to the dialog`

As result, i cannot retrieve events from that dialogs. And when try to send a message to one of them - it delivered to that one, i was joined.

Before join i perform:
1. QB.settings.init()
2. QB.settings.enableAutoReconnect({enable:true})
3. QB.chat.connect()
4. QB.chat.getDialogs()

Platform: IOS

RN info:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 36.05 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0 => 0.61.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 14:36
@Gusakovskyi Hello,

This is Nikolay from QuickBlox support.

Please make sure that you followed our documentation and if you have a correct session:
[https://docs.quickblox.com/docs/react-native-authentication](https://docs.quickblox.com/docs/react-native-authentication)

Please let me know if the issue is still relevant.
If yes, please provide me with the following points:
1. Version of QuickBlox React Native SDK.
2. Platform where the issue is reproduced (Android, iOS, or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. React Native version.
5 Current information from react-native info.
6. Information from npm list.
7. Device models.
8. Step-by-step instructions on how to reproduce the issue.
9. Full logs.

**Comment by ghost** [comment] 2021-12-07 14:19
@Gusakovskyi The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:19 UTC
