### ISSUE TITLE
Error Call API 

### ISSUE THREAD

**Issue by kimivn** [QuickBlox/quickblox-react-native-sdk#14] opened 2020-05-22 04:41 UTC
I have a new issue when use call api
 **You have to be logged in in order to use Chat API**
. Before I inited appSettings and login Users successfully and get data user. I don't why i use a call api but error in Chat Api

Please help me.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-07 09:58
Hello @kimivn 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if you reviewed our documentation:
[https://docs.quickblox.com/docs/react-native-authentication](https://docs.quickblox.com/docs/react-native-authentication)

Also, please try using our React Native Chat sample:
[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample)

**Comment by ghost** [comment] 2021-12-07 14:20
@kimivn The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:20 UTC
