### ISSUE TITLE
Message received in wrong dialog on IOS

### ISSUE THREAD

**Issue by hussnainghani** [QuickBlox/quickblox-react-native-sdk#25] opened 2020-11-26 16:49 UTC
Hello team Quickblox!

I'm facing one issue in Group Chat only for IOS on android working fine.

i have created group dialog and send message in that dialog but that message received in an other dialog not in that in which i sent message.

i use this code to send message:
```
QB.chat
      .sendMessage({
        dialogId: '5fb9ccd9a28f9a6bb09a2b75',
        body: 'Hello World',
        saveToHistory: true,
      })
      .then(() => {
      })
      .catch(async function (e) {
        console.log(e);
      });
```

message sent successfully and when message received in callback for new message received.
here's code for message received callback

```
Event_RECEIVED_NEW_MESSAGE = emitter.addListener(
      QB.chat.EVENT_TYPE.RECEIVED_NEW_MESSAGE,
      receivedNewMessage,
    );

   const receivedNewMessage = (event) => {
      console.log('event');
      console.log(event);
   };
```

output of console.log(event); is here:
```
{"payload": {"body": "Ewfew", "dateSent": 1606404944000, "delayed": false, "deliveredIds": [124116987], "dialogId": "5fbeb3bda0eb472422215829", "id": "5fbfcb501b39681819d63b35", "markable": true, "properties": {"date_sent": "1606404944", "dialog_id": "5fbeb3bda0eb472422215829", "message_id": "5fbfcb501b39681819d63b35", "save_to_history": "1"}, "readIds": [124116987], "recipientId": 124116987, "saveToHistory": true, "senderId": 124116987}, "type": "@QB/RECEIVED_NEW_MESSAGE"}
```

You see notice i sent message to `5fb9ccd9a28f9a6bb09a2b75` this dialog but message saved in wrong dialog in event logs you can see that dialog id is `5fbfcb501b39681819d63b35`

`5fbfcb501b39681819d63b35` this is the id of first dialog which i was created for this user.
when i send message in any dialog that message always received in `5fbfcb501b39681819d63b35` this dialog.

This issue is only for IOS on Android working fine.

Thanks in advance please help me to resolve this issue because that is really urgent for me.

**Comment by rmethaniya** [comment] 2020-12-09 09:08
Hello, I am facing the same for public dialog and I have debug code and review documentation and found that they have change API parameter for API get dialogDetail. You can check bellow link for that

https://docs.quickblox.com/reference/chat#list-dialogs

For fix issue in iOS follow bellow step
**File Location** : node_modules/quickblox-react-native-sdk/ios/QBPlatformCore/QBCore/QBChat
**File** : QBChatModule.m
**Function** : dialogWithInfo and in this function you will find bellow code

`QBResponsePage *responsePage = [QBResponsePage responsePageWithLimit:1 skip:0];`
` NSDictionary *extendedRequest = @{@"id": dialogId};`

For fix this issue you have **replace id with _id** so it should be
`NSDictionary *extendedRequest = @{@"_id": dialogId};`

After this change it will work.

**Comment by hussnainghani** [comment] 2020-12-31 17:04
@rmethaniya thank for solution that work's for me.
but issue still exist in quickblox package.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:42
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 14:17
@hussnainghani Hello,

This is Nikolay from QuickBlox support.

Please try updating the SDK and let me know if the issue is still relevant:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)

If yes, please provide me with the following points:
1. Steps to reproduce the issue.
2. Full logs.
3. iOS version.
4. React Native version.
5. Information from react-native info.
6. Information from npm list.

**Comment by ghost** [comment] 2021-12-07 14:22
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:22 UTC
