### ISSUE TITLE
TypeError: Cannot read property 'addListener' of undefined (on iOS)

### ISSUE THREAD

**Issue by amir-gorji** [QuickBlox/quickblox-react-native-sdk#17] opened 2020-06-09 13:03 UTC
I use quickblox-react-native-sdk@0.5.2-beta as a service for video calling and chatting.
It runs fine on android , but when I run on iOS, it brings up an error.

> TypeError: Cannot read property 'addListener' of undefined

I searched all my code several times, I added all the iOS pods of the quickblox-samples but the problem persists.
I edited the `${project_directory}/node_modules/quickblox-react-native-sdk/index.js` line 639:
`addListener: Chat.addListener` ---> `addListener: Chat && Chat.addListener`.
The error disappeared then next error `removeListeners of undefined`. I guess the error is about nativeModules' compatibility with iOS.

I use react native@0.61.5 and I tested on several android phones (all doing great).
one iPad and several types of iPhone emulators they're all having the same error.
By the way the app was working fine both on android and iOS before using quickblox.
Nothing changed in my app but codes related to quickblox.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:43
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by ghost** [comment] 2021-10-06 14:22
@amir-gorji Hello,

This is Nikolay from QuickBlox support.

Please let me know if you followed our documentation and if the issue is still relevant.
Here is a link to the documentation:
[https://docs.quickblox.com/docs/react-native-quick-start](https://docs.quickblox.com/docs/react-native-quick-start)

**Comment by ghost** [comment] 2021-12-07 14:21
@amir-gorji The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 14:21 UTC
