### ISSUE TITLE
fullscreen video in landscape

### ISSUE THREAD

**Issue by ayushjain1796** [QuickBlox/quickblox-react-native-sdk#26] opened 2020-12-14 14:32 UTC
Has anyone make the changes for remote video to be in full screen and local video in small window in landscape mode.

For portrait mode my changes are working fine.

**Comment by ghost** [comment] 2021-10-06 13:10
@ayushjain1796 Hello,

This is Nikolay from QuickBlox support.

Please update the SDK to the latest version and let me know if the issue is resolved:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)

**Comment by ayushjain1796** [comment] 2021-10-06 13:51
@QB-nikolay-zolotarov hi, 

can you please confirm that the latest sdk support the video call functionality in landscape mode?

**Comment by ghost** [comment] 2021-10-07 12:35
@ayushjain1796 
According to my check, some issues with resolution were be fixed in the latest SDK.

At this point, I can suggest updating the SDK so we can investigate issues with the latest version as some issues could be fixed.

**Closed as completed** 2023-01-12 10:48 UTC
